workspace:
  base: .
  path: /

pipeline:
  publish:
    image: plugins/docker
    privileged: true
    settings:
      repo: stkw0/test-image
      tags:
        - stkw0/test-image:latest
      username: stkw0
      password:
        from_secret: docker_password
