workspace:
  base: .
  path: /

pipeline:
  build:
    image: gentoo/stage3-amd64
    privileged: true
    commands:
      - emerge-webrsync -q
      - echo "ACCEPT_KEYWORDS="~amd64"" >> /etc/portage/make.conf
      - echo "MAKEOPTS="-j8"" >> /etc/portage/make.conf
      - emerge --autounmask --autounmask-continue --ask=n -quUDN --with-bdeps=y @world --exclude metalog
      - emerge --autounmask --autounmask-continue --ask=n -q clang cppcheck
